import smtplib
from email.message import EmailMessage

SENDER = "flashstudyv2@gmail.com"
APP_PASSWORD = "blwmbozsrepcohge"

def send_report(email,username,filename):
    msg = EmailMessage()
    msg['Subject'] = "Monthly Progress Report"
    msg["From"] = SENDER
    msg["To"] = email
    body = "Hi {},\nPlease find below your progress report for this month.".format(username)
    signoff = "Regards\nFalshStudy\nThis message was generated by an automated system. Please do not reply to it."
    econtent = body+"\n\n\n"+signoff
    msg.set_content(econtent)

    with open("proc/{}.pdf".format(filename)) as f:
        report = f.read()
        name = f.name
    msg.add_attachment(report,filename=name)

    with smtplib.SMTP_SSL("smtp.gmail.com",465) as smtp:
        smtp.login(SENDER,APP_PASSWORD)        
        smtp.send_message(msg)

send_report("sourabhw7@gmail.com","sourabh","testfile")