import smtplib
from email.message import EmailMessage

SENDER = "<your-email>"
APP_PASSWORD = "<your-app-password>"

def send_reminder(email,username):
    msg = EmailMessage()
    msg['Subject'] = "Daily Revision Reminder"
    msg["From"] = SENDER
    msg["To"] = email
    body = "Hi {},\nThis is a reminder to revise on Flash Study today.\n\nHappy learning! :)".format(username)
    signoff = "This message was generated by an automated system. Please do not reply to it."
    econtent = body+"\n\n\n"+signoff
    msg.set_content(econtent)
    with smtplib.SMTP_SSL("smtp.gmail.com",465) as smtp:
        smtp.login(SENDER,APP_PASSWORD)        
        smtp.send_message(msg)

#FIXED
def send_report(email,username,filename):
    msg = EmailMessage()
    msg['Subject'] = "Monthly Progress Report"
    msg["From"] = SENDER
    msg["To"] = email
    body = "Hi {},\nPlease find below your progress report for this month.".format(username)
    signoff = "Regards\nFalshStudy\nThis message was generated by an automated system. Please do not reply to it."
    econtent = body+"\n\n\n"+signoff
    msg.set_content(econtent)
    with open("proc/{}.pdf".format(filename),'rb') as f:
        report = f.read()
        name = f.name
    msg.add_attachment(report,filename=name,maintype='application',subtype='octet-stream')
    with smtplib.SMTP_SSL("smtp.gmail.com",465) as smtp:
        smtp.login(SENDER,APP_PASSWORD)        
        smtp.send_message(msg)
