import smtplib
from email.message import EmailMessage

SENDER = "flashstudyv2@gmail.com"
APP_PASSWORD = "blwmbozsrepcohge"

def send_reminder(email,username):
    msg = EmailMessage()
    msg['Subject'] = "Daily Revision Reminder"
    msg["From"] = SENDER
    msg["To"] = email
    body = "Hi {},\nThis is a reminder to revise on Flash Study today.\n\nHappy learning! :)".format(username)
    signoff = "This message was generated by an automated system. Please do not reply to it."
    econtent = body+"\n\n\n"+signoff
    msg.set_content(econtent)
    with smtplib.SMTP_SSL("smtp.gmail.com",465) as smtp:
        smtp.login(SENDER,APP_PASSWORD)        
        smtp.send_message(msg)

#send_reminder("sourabhw7@gmail.com","sourabh")